/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:45.498 14586 WARNING neutron.agent.securitygroups_rpc [-] Driver configuration doesn't match with enable_security_group
/root/openstack/logs/2017-02-09/0804/nova-novncproxy.log:2017-02-09 07:43:45.528 14581 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:43:45.632 14608 WARNING stevedore.named [req-d074e04a-1d0e-41b9-9727-097849c76ac2 - - - - -] Could not load neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:45.634 14586 WARNING oslo_db.sqlalchemy.engines [-] SQL connection failed. 10 attempts left.
/root/openstack/logs/2017-02-09/0804/mysqld.log:2017-02-09 07:43:46 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
/root/openstack/logs/2017-02-09/0804/mysqld.log:2017-02-09 07:43:46 15093 [Warning] Buffered warning: Changed limits: max_connections: 214 (requested 500)
/root/openstack/logs/2017-02-09/0804/mysqld.log:2017-02-09 07:43:46 15093 [Warning] Buffered warning: Changed limits: max_open_files: 1024 (requested 5000)
/root/openstack/logs/2017-02-09/0804/mysqld.log:2017-02-09 07:43:46 15093 [Warning] Buffered warning: Changed limits: table_open_cache: 400 (requested 2000)
/root/openstack/logs/2017-02-09/0804/nova-consoleauth.log:2017-02-09 07:43:46.616 14575 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/nova-conductor.log:2017-02-09 07:43:46.643 14579 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/nova-api.log:2017-02-09 07:43:46.683 14572 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/nova-compute.log:2017-02-09 07:43:46.966 14631 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/nova-scheduler.log:2017-02-09 07:43:47.125 14577 WARNING oslo_reports.guru_meditation_report [-] Guru meditation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
/root/openstack/logs/2017-02-09/0804/nova-compute.log:2017-02-09 07:43:47.270 14631 WARNING os_brick.initiator.connectors.remotefs [req-c3ddc3d7-bc27-4274-9d1c-b93fbb208d83 - - - - -] Connection details not present. RemoteFsClient may not initialize properly.
/root/openstack/logs/2017-02-09/0804/nova-compute.log:2017-02-09 07:43:48.695 14631 WARNING nova.compute.monitors [req-5611e8e2-ac56-4ff4-a941-7d01a2a097d6 - - - - -] Excluding nova.compute.monitors.cpu monitor virt_driver. Not in the list of enabled monitors (CONF.compute_monitors).
/root/openstack/logs/2017-02-09/0804/nova-compute.log:2017-02-09 07:43:49.244 14631 WARNING nova.scheduler.client.report [req-5611e8e2-ac56-4ff4-a941-7d01a2a097d6 - - - - -] No authentication information found for placement API. Optional use of placement API for reporting is now disabled.
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.850 14586 WARNING neutron.agent.securitygroups_rpc [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Driver configuration doesn't match with enable_security_group
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.910 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension dns-integration not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.917 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension ip_allocation not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.917 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension l2_adjacency not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.923 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension metering not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.933 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension qos not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.937 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension router-service-type not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.940 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension segment not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.946 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension trunk not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.947 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension trunk-details not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:43:55.948 14586 WARNING neutron.api.extensions [req-ce6d7af0-53bc-4199-8423-ff06965c026a - - - - -] Extension vlan-transparent not supported by any of loaded plugins
/root/openstack/logs/2017-02-09/0804/nova-compute.log:2017-02-09 07:44:07.862 14631 WARNING nova.compute.manager [-] [instance: efca1ee1-f6dd-4aea-b584-775c7b2de29b] Instance shutdown by itself. Calling the stop API. Current vm_state: active, current task_state: None, original DB power_state: 1, current VM power_state: 4
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:44:44.206 15469 WARNING neutron.db.agentschedulers_db [req-09254073-ffe7-42cb-bed8-ee044a757931 - - - - -] No DHCP agents available, skipping rescheduling
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent 
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent [-] Failed reporting state!
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/metadata/agent.py", line 262, in _report_state
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent MessagingTimeout: Timed out waiting for a reply to message ID d35e35b3430f4e38a0e3112782d07965
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     retry=retry)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     retry=self.retry)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.129 14588 ERROR neutron.agent.metadata.agent     use_call=self.agent_state.get('start_flag'))
/root/openstack/logs/2017-02-09/0804/metadata-agent.log:2017-02-09 07:44:45.132 14588 WARNING oslo.service.loopingcall [-] Function 'neutron.agent.metadata.agent.UnixDomainMetadataProxy._report_state' run outlasted interval by 30.06 sec
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     ctx, self.agent_state, True)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 687, in _report_state
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent MessagingTimeout: Timed out waiting for a reply to message ID 5c627ed063ca4df9a50c2d306349f97d
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent [req-5c959a0b-e58b-467d-b7fe-be3732bcc6d7 - - - - -] Failed reporting state!
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     retry=retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     retry=self.retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.137 14587 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.142 14587 WARNING oslo.service.loopingcall [req-5c959a0b-e58b-467d-b7fe-be3732bcc6d7 - - - - -] Function 'neutron.agent.dhcp.agent.DhcpAgentWithStateReport._report_state' run outlasted interval by 30.06 sec
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.143 14587 ERROR neutron.common.rpc [req-82cfc849-e45e-43dd-88b0-a69bfeca176e - - - - -] Timeout in RPC method get_active_networks_info. Waiting for 7 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:45.144 14587 WARNING neutron.common.rpc [req-82cfc849-e45e-43dd-88b0-a69bfeca176e - - - - -] Increasing timeout for get_active_networks_info calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-09/0804/l3-agent.log:2017-02-09 07:44:45.170 14591 ERROR neutron.common.rpc [req-ca70f015-d67d-4c43-9782-8d633bdb5368 - - - - -] Timeout in RPC method get_service_plugin_list. Waiting for 5 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-09/0804/l3-agent.log:2017-02-09 07:44:45.172 14591 WARNING neutron.common.rpc [req-ca70f015-d67d-4c43-9782-8d633bdb5368 - - - - -] Increasing timeout for get_service_plugin_list calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent 
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent [-] Failed reporting state!
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 88, in report_state
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/openvswitch/agent/ovs_neutron_agent.py", line 320, in _report_state
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent MessagingTimeout: Timed out waiting for a reply to message ID 87480171b61f4f74915423eda938b6a0
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     retry=retry)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     retry=self.retry)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     return method(context, 'report_state', **kwargs)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent Traceback (most recent call last):
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.712 14608 ERROR neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent     True)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:45.715 14608 WARNING oslo.service.loopingcall [-] Function 'neutron.plugins.ml2.drivers.openvswitch.agent.ovs_neutron_agent.OVSNeutronAgent._report_state' run outlasted interval by 30.05 sec
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:46.093 14608 ERROR neutron.common.rpc [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Timeout in RPC method tunnel_sync. Waiting for 50 seconds before next attempt. If the server is not down, consider increasing the rpc_response_timeout option as Neutron server(s) may be overloaded and unable to respond quickly enough.
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:44:46.094 14608 WARNING neutron.common.rpc [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Increasing timeout for tunnel_sync calls to 120 seconds. Restart the agent to restore it to the default value.
/root/openstack/logs/2017-02-09/0804/l3-agent.log:2017-02-09 07:44:50.440 14591 WARNING neutron.agent.l3.agent [req-ca70f015-d67d-4c43-9782-8d633bdb5368 - - - - -] l3-agent cannot contact neutron server to retrieve service plugins enabled. Check connectivity to neutron server. Retrying... Detailed message: Timed out waiting for a reply to message ID dc24125235c2408b9922844ab139c257.
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent 
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     active_networks = self.plugin_rpc.get_active_networks_info()
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 159, in sync_state
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp/agent.py", line 522, in get_active_networks_info
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 138, in call
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 157, in call
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 238, in get
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 336, in wait
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 453, in _send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 464, in send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/client.py", line 169, in call
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 97, in _send
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     host=self.host)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     message = self.waiters.get(msg_id, timeout=timeout)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent MessagingTimeout: Timed out waiting for a reply to message ID 270d2e0cc9084e7e9f38361576883063
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent [req-82cfc849-e45e-43dd-88b0-a69bfeca176e - - - - -] Unable to sync network state.
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     result = self._waiter.wait(msg_id, timeout)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     retry=retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     retry=self.retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     return self._original_context.call(ctxt, method, **kwargs)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     self.force_reraise()
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     six.reraise(self.type_, self.value, self.tb)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     timeout=timeout, retry=retry)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     time.sleep(wait)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent     'to message ID %s' % msg_id)
/root/openstack/logs/2017-02-09/0804/dhcp-agent.log:2017-02-09 07:44:51.690 14587 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.048 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.457s, table=0, n_packets=0, n_bytes=0, idle_age=2624, priority=10,icmp6,in_port=32,icmp_type=136 actions=resubmit(,24)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.058 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.442s, table=0, n_packets=3, n_bytes=126, idle_age=2549, priority=10,arp,in_port=32 actions=resubmit(,24)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.066 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.474s, table=0, n_packets=135, n_bytes=13312, idle_age=2554, priority=9,in_port=32 actions=resubmit(,25)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.075 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.465s, table=24, n_packets=0, n_bytes=0, idle_age=2624, priority=2,icmp6,in_port=32,icmp_type=136,nd_target=fe80::f816:3eff:fe10:a760 actions=NORMAL
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.084 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.450s, table=24, n_packets=3, n_bytes=126, idle_age=2549, priority=2,arp,in_port=32,arp_spa=192.168.2.6 actions=resubmit(,25)
/root/openstack/logs/2017-02-09/0804/openvswitch-agent.log:2017-02-09 07:45:38.093 14608 WARNING neutron.plugins.ml2.drivers.openvswitch.agent.openflow.ovs_ofctl.ofswitch [req-f1dfd205-9f42-4aa6-9478-1c04ad5f4dd7 - - - - -] Deleting flow  cookie=0xbd1e6c3356ec869d, duration=2624.488s, table=25, n_packets=138, n_bytes=13438, idle_age=2549, priority=2,in_port=32,dl_src=fa:16:3e:10:a7:60 actions=NORMAL
/root/openstack/logs/2017-02-09/0804/server.log:2017-02-09 07:45:38.147 15467 WARNING neutron.plugins.ml2.drivers.type_tunnel [req-d074e04a-1d0e-41b9-9727-097849c76ac2 - - - - -] Endpoint with ip x.x.x.2 already exists
/root/openstack/logs/2017-02-09/0804/api.log:2017-02-09 08:00:38.803 14941 WARNING oslo_config.cfg [req-1c28e0d5-e42e-40f1-8d8b-381945a1d872 fbf650853680448684c3eea8d2a6d0b7 e9f7777a80214091867a0e8bca2d8a22 - default default] Option "sql_connection" from group "DEFAULT" is deprecated. Use option "connection" from group "database".
